//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public double Price { get; set; }
        public bool CategoryFk { get; set; }
        public string ImgName { get; set; }
        public int MenuFk { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Menu Menu { get; set; }
    }
}
